"""
models/notification.py
-----------------------
Simple in-app notifications, e.g. "Your pickup was accepted",
"Handover completed". Generated by other services (pickup_service,
handover_service, payment_service) as things happen — not created
directly by users.
"""

import uuid

from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.database import Base


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))

    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    title = Column(String, nullable=False)
    message = Column(String, nullable=False)

    # Free-text category, e.g. "PICKUP_ACCEPTED", "HANDOVER_COMPLETED".
    # Kept as a plain string (not an enum) since new notification types
    # will likely be added often as the app grows, and a string avoids
    # a database migration every time a new type is introduced.
    type = Column(String, nullable=False)

    read = Column(Boolean, default=False, nullable=False, index=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user = relationship("User")

    def __repr__(self):
        return f"<Notification id={self.id} user_id={self.user_id} type={self.type} read={self.read}>"
