import { useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { Camera, Upload, Image as ImageIcon } from 'lucide-react'
import { PageHeader } from '../../components/PageHeader'
import { AppLayout } from '../../layouts/AppLayout'
import { useApp } from '../../contexts/AppContext'
export function PhotoUpload(){const nav=useNavigate();const {setDraft}=useApp();const handle=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(file){setDraft({photoUrl:URL.createObjectURL(file)});nav('/collector/add/material')}};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Add scrap"/><div className="card p-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-leaf text-white font-bold">1</div><div><div className="font-bold">Photo</div><div className="text-sm text-gray-500">Take or choose a photo</div></div></div><label className="flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-leaf/30 bg-mint text-center"><Camera size={44} className="text-leaf"/><span className="mt-4 font-bold">Take photo / choose image</span><span className="mt-1 text-sm text-gray-500">Camera permission may be unavailable in a prototype</span><input type="file" accept="image/*" capture="environment" onChange={handle} className="hidden"/></label><button onClick={()=>nav('/collector/add/material')} className="secondary mt-4 w-full"><Upload size={19}/> Continue without photo</button></div></div></AppLayout>}
export function MaterialSelection(){const {setDraft,demo}=useApp();const nav=useNavigate();return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Choose material"/><div className="grid grid-cols-2 gap-3">{['Copper','Aluminium','PCB','LCD','CRT','Battery','Cable','Plastic','Other'].map(name=>{const selected=demo.draft.materialId===name;return <button key={name} onClick={()=>{const id={'Copper':'MAT001','Aluminium':'MAT002','PCB':'MAT003','LCD':'MAT004','CRT':'MAT005','Battery':'MAT006','Cable':'MAT007','Plastic':'MAT008','Other':'MAT009'}[name]!;setDraft({materialId:id});nav('/collector/add/weight')}} className={`card flex min-h-28 flex-col items-center justify-center gap-2 p-4 text-center font-bold ${selected?'border-2 border-leaf bg-mint':''}`}><ImageIcon className="text-leaf"/>{name}</button>})}</div></div></AppLayout>}
export function Weight(){const {setDraft}=useApp();const [value,setValue]=useState('10');const nav=useNavigate();const [error,setError]=useState('');return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Estimated weight"/><div className="card p-6"><label className="label">Weight in kg</label><input autoFocus inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} className="h-20 w-full rounded-2xl border border-black/10 px-5 text-3xl font-black outline-none focus:border-leaf"/>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button className="primary mt-5 w-full" onClick={()=>{const n=Number(value);if(!Number.isFinite(n)||n<=0){setError('Weight must be greater than zero.');return}setDraft({weight:n});nav('/collector/add/condition')}}>Continue</button></div></div></AppLayout>}
export function Condition(){const {setDraft}=useApp();const nav=useNavigate();return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Condition"/><div className="space-y-3">{(['GOOD','MIXED','DAMAGED'] as const).map(c=><button key={c} className="card flex w-full items-center justify-between p-5 text-left" onClick={()=>{setDraft({condition:c});nav('/collector/add/review')}}><div><div className="text-lg font-black">{c==='GOOD'?'Good':c==='MIXED'?'Mixed':'Damaged'}</div><div className="text-sm text-gray-500">{c==='GOOD'?'Mostly clean and usable':c==='MIXED'?'Different grades together':'Broken or heavily worn'}</div></div><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-leaf">Select</span></button>)}</div></div></AppLayout>}
export function LotReview(){const {demo,setDraft}=useApp();const nav=useNavigate();const [loading,setLoading]=useState(false);const [error,setError]=useState('');const create=async()=>{if(loading)return;const {materialId,weight,condition,photoUrl}=demo.draft;if(!materialId||!weight||!condition){setError('Missing lot data. Go back and complete each step.');return}try{setLoading(true);const {lotService}=await import('../../services');const lot=await lotService.createLot({client_request_id:`LOCAL-${Date.now()}`,material_id:materialId,estimated_weight:weight,condition,photo_url:photoUrl});setDraft({});import('../../contexts/AppContext').then(()=>{});nav(`/collector/lot-created/${lot.id}`)}catch(e){setError(e instanceof Error?e.message:'Could not create lot')}finally{setLoading(false)}};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Review lot"/><div className="card p-6 space-y-4"><Row label="Material" value={demo.draft.materialId?.replace('MAT00','')||'—'}/><Row label="Weight" value={`${demo.draft.weight??'—'} kg`}/><Row label="Condition" value={demo.draft.condition||'—'}/><div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Prototype note: the backend remains the final authority for prices and financial calculations.</div>{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}<button disabled={loading} onClick={create} className="primary w-full">{loading?'Creating…':'Create Lot'}</button></div></div></AppLayout>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between border-b border-black/5 py-3"><span className="text-gray-500">{label}</span><strong>{value}</strong></div>}

