import { useEffect,useState } from 'react'
import { QrCode, ShieldCheck } from 'lucide-react'
import { AppLayout } from '../../layouts/AppLayout'
import { PageHeader } from '../../components/PageHeader'
import { handoverService,lotService,priceService,pickupService } from '../../services'
import { useApp } from '../../contexts/AppContext'
import { formatINR } from '../../utils/storage'
export default function Handover(){const {demo,updateDemo}=useApp();const [lot,setLot]=useState<any>(null);const [price,setPrice]=useState(0);const [weight,setWeight]=useState('10');const [loading,setLoading]=useState(false);const [error,setError]=useState('');useEffect(()=>{if(demo.selectedLotId){lotService.getLot(demo.selectedLotId).then(l=>{setLot(l);priceService.getPrice(l.material.id).then(p=>setPrice(p.current_price))})}},[demo.selectedLotId]);const final=Number(weight)>0?Number(weight)*price:0;const submit=async()=>{if(!lot||!demo.selectedPickupId||Number(weight)<=0){setError('Missing data or invalid actual weight.');return}try{setLoading(true);const ref=`QR-${lot.id}`;const h=await handoverService.complete({lotId:lot.id,pickupId:demo.selectedPickupId,actualWeight:Number(weight),agreedPrice:price,verificationReference:ref});updateDemo({handover:{actualWeight:h.actual_weight,agreedPrice:h.agreed_price,verificationReference:ref}});setLoading(false)}catch(e){setError(e instanceof Error?e.message:'Handover failed');setLoading(false)}};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Handover"/>{!lot?<div className="card p-6">Select a lot first.</div>:<div className="space-y-3"><div className="card p-6 space-y-3"><Row l="Lot ID" v={lot.id}/><Row l="Estimated weight" v={`${lot.estimated_weight} kg`}/><label className="label mt-4">Actual weight</label><input type="number" min="0.01" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} className="h-14 w-full rounded-2xl border px-4 text-xl font-bold"/><Row l="Agreed price" v={`${formatINR(price)}/kg`}/><Row l="Final amount" v={formatINR(final)}/>{error&&<div className="rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<button disabled={loading} className="primary w-full" onClick={submit}>{loading?'Confirming…':'Confirm handover'}</button></div><div className="card p-6 text-center"><QrCode size={54} className="mx-auto text-leaf"/><h2 className="mt-3 text-xl font-black">QR verification</h2><p className="mt-1 text-sm text-gray-500">Mock verification component. This QR is not cryptographically secure.</p><div className="mx-auto mt-4 w-fit rounded-xl bg-ink px-4 py-2 font-mono text-sm text-white">QR-{lot.id}</div>{demo.handover&&<div className="mt-4 inline-flex items-center gap-2 rounded-full bg-mint px-3 py-2 text-sm font-bold text-leaf"><ShieldCheck size={16}/> Verified for prototype</div>}</div>{demo.handover&&<button className="primary w-full" onClick={()=>window.location.assign('/collector/payment')}>Continue to payment</button>}</div>}</div></AppLayout>}
function Row({l,v}:{l:string;v:string}){return <div className="flex justify-between border-b border-black/5 py-2 text-sm"><span className="text-gray-500">{l}</span><strong>{v}</strong></div>}
