import { useEffect,useState } from 'react'
import { Package, ChevronRight } from 'lucide-react'
import { Link, useParams, useNavigate } from 'react-router-dom'
import { AppLayout } from '../../layouts/AppLayout'
import { PageHeader } from '../../components/PageHeader'
import { StateCard } from '../../components/StateCard'
import { lotService } from '../../services'
import type { Lot } from '../../types'
import { formatINR,formatDate } from '../../utils/storage'
export default function Lots(){const [lots,setLots]=useState<Lot[]>([]);const [loading,setLoading]=useState(true);const load=()=>{setLoading(true);lotService.getLots().then(setLots).finally(()=>setLoading(false))};useEffect(load,[]);return <AppLayout><div className="mx-auto max-w-3xl"><PageHeader title="My lots"/>{loading?<StateCard state="loading" message="Loading lots…"/>:lots.length===0?<StateCard state="empty" message="No lots yet. Add your first scrap lot."/>:<div className="space-y-3">{lots.map(l=><Link to={`/collector/lots/${l.id}`} key={l.id} className="card flex items-center gap-4 p-5"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-mint text-leaf"><Package/></div><div className="flex-1"><div className="font-black">{l.material.name} · {l.estimated_weight} kg</div><div className="mt-1 text-sm text-gray-500">{l.id} · {formatDate(l.created_at)}</div><div className="mt-2 flex gap-2"><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold">{l.status.replaceAll('_',' ')}</span>{l.pendingSync&&<span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800">PENDING_SYNC</span>}</div></div><div className="text-right"><div className="font-black">{formatINR(l.estimated_value)}</div><ChevronRight className="ml-auto mt-2 text-gray-400"/></div></Link>)}</div>}</div></AppLayout>}
export function LotDetails(){const {id}=useParams();const [lot,setLot]=useState<Lot|null>(null);const nav=useNavigate();useEffect(()=>{if(id)lotService.getLot(id).then(setLot)},[id]);if(!lot)return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Lot details"/><StateCard state="loading" message="Loading lot…"/></div></AppLayout>;return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Lot details"/><div className="card p-6"><div className="rounded-2xl bg-mint p-5"><div className="text-sm text-gray-500">Lot ID</div><div className="text-2xl font-black">{lot.id}</div></div><div className="mt-5 space-y-1"><Row l="Material" v={lot.material.name}/><Row l="Estimated weight" v={`${lot.estimated_weight} kg`}/><Row l="Actual weight" v={lot.actual_weight?`${lot.actual_weight} kg`:'—'}/><Row l="Condition" v={lot.condition}/><Row l="Status" v={lot.status}/><Row l="Estimated value" v={formatINR(lot.estimated_value)}/></div>{lot.status==='COMPLETED'&&<button className="primary mt-5 w-full" onClick={()=>nav('/collector/earnings')}>View earnings</button>}{lot.status==='CREATED'&&<button className="primary mt-5 w-full" onClick={()=>nav(`/collector/recyclers?lot=${lot.id}`)}>Find recycler</button>}</div></div></AppLayout>}
function Row({l,v}:{l:string;v:string}){return <div className="flex justify-between border-b border-black/5 py-3"><span className="text-gray-500">{l}</span><strong>{v}</strong></div>}
