import { useState } from 'react'
import { Banknote, CheckCircle2, Smartphone } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppLayout } from '../../layouts/AppLayout'
import { PageHeader } from '../../components/PageHeader'
import { paymentService,transactionService } from '../../services'
import { useApp } from '../../contexts/AppContext'
import { formatINR } from '../../utils/storage'
export default function Payment(){const {demo}=useApp();const [method,setMethod]=useState<'UPI'|'CASH'>('UPI');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [failed,setFailed]=useState(false);const [paid,setPaid]=useState(false);const nav=useNavigate();const amount=demo.handover?demo.handover.actualWeight*demo.handover.agreedPrice:0;const pay=async()=>{if(!demo.handover||amount<=0){setError('Missing handover data.');return}setLoading(true);setError('');setFailed(false);try{const tx=await transactionService.createTransaction({lotId:demo.selectedLotId||'UNKNOWN',material:'Copper',weight:demo.handover.actualWeight,amount,payment_method:method,payment_status:'PENDING'});await paymentService.pay(tx.id,method,false);setPaid(true)}catch(e){setFailed(true);setError(e instanceof Error?e.message:'Payment failed')}finally{setLoading(false)}};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Payment"/><div className="card p-6"><div className="text-sm text-gray-500">Final amount</div><div className="mt-1 text-4xl font-black">{formatINR(amount)}</div><div className="mt-6 grid grid-cols-2 gap-3">{([['UPI',Smartphone],['CASH',Banknote]] as [ 'UPI'|'CASH', typeof Smartphone ][]).map(([m,Icon])=><button key={m} onClick={()=>setMethod(m as 'UPI'|'CASH')} className={`rounded-2xl border p-5 ${method===m?'border-leaf bg-mint text-leaf':'border-black/10'}`}><Icon className="mx-auto"/><div className="mt-2 font-bold">{m}</div></button>)}</div>{error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-semibold text-red-700">Payment failed: {error}. It is not marked as successful.</div>}{paid?<div className="mt-5 text-center"><CheckCircle2 size={54} className="mx-auto text-leaf"/><h2 className="mt-2 text-xl font-black">Payment paid</h2><button className="primary mt-4 w-full" onClick={()=>nav('/collector/earnings')}>View earnings</button></div>:<button disabled={loading||failed} className="primary mt-5 w-full" onClick={pay}>{loading?'Processing…':failed?'Retry payment':'Simulate payment'}</button>}</div></div></AppLayout>}
