import { useEffect,useState } from 'react'
import { Check, Clock3, MapPin, Truck, UserCheck } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AppLayout } from '../../layouts/AppLayout'
import { PageHeader } from '../../components/PageHeader'
import { pickupService,recyclerService } from '../../services'
import { useApp } from '../../contexts/AppContext'
import type { Pickup, PickupStatus } from '../../types'
const steps:PickupStatus[]=['REQUESTED','ACCEPTED','ASSIGNED','ON_THE_WAY','ARRIVED','HANDOVER','COMPLETED']
export function PickupRequest(){const {demo,updateDemo}=useApp();const nav=useNavigate();const [loading,setLoading]=useState(false);const submit=async()=>{if(!demo.selectedLotId||!demo.selectedRecyclerId)return;setLoading(true);const p=await pickupService.createPickup(demo.selectedLotId,demo.selectedRecyclerId);updateDemo({selectedPickupId:p.id});setLoading(false);nav('/collector/pickup/tracking')};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Request pickup"/><div className="card p-6"><p className="text-sm text-gray-500">Lot</p><p className="font-black">{demo.selectedLotId||'—'}</p><p className="mt-4 text-sm text-gray-500">Recycler</p><p className="font-black">{demo.selectedRecyclerId||'—'}</p><button disabled={loading||!demo.selectedLotId||!demo.selectedRecyclerId} className="primary mt-6 w-full" onClick={submit}>{loading?'Requesting…':'Request pickup'}</button></div></div></AppLayout>}
export function PickupTracking(){const {demo}=useApp();const [pickup,setPickup]=useState<Pickup|null>(null);const [recyclerName,setRecyclerName]=useState('Recycler');const nav=useNavigate();useEffect(()=>{if(demo.selectedPickupId)pickupService.getPickup(demo.selectedPickupId).then(setPickup);if(demo.selectedRecyclerId)recyclerService.getAll().then(rs=>setRecyclerName(rs.find(r=>r.recycler_id===demo.selectedRecyclerId)?.name||'Recycler'))},[demo.selectedPickupId,demo.selectedRecyclerId]);if(!pickup)return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Pickup tracking"/><div className="card p-6 text-center text-gray-500">No pickup selected.</div></div></AppLayout>;const advance=async()=>{const i=steps.indexOf(pickup.status);if(i<steps.length-1){const next=await pickupService.updateStatus(pickup.id,steps[i+1]);setPickup(next)}};return <AppLayout><div className="mx-auto max-w-xl"><PageHeader title="Pickup tracking"/><div className="card p-6"><div className="rounded-2xl bg-mint p-4"><div className="text-sm text-gray-500">Recycler</div><div className="font-black">{recyclerName}</div><div className="mt-1 text-sm text-leaf font-bold">{pickup.status.replaceAll('_',' ')}</div></div><div className="mt-6 space-y-1">{steps.map((s,i)=>{const current=steps.indexOf(pickup.status);const done=i<=current;return <div key={s} className="flex items-start gap-3"><div className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${done?'bg-leaf text-white':'bg-gray-100 text-gray-400'}`}>{done?<Check size={16}/>:<Clock3 size={16}/>}</div><div className="pb-5"><div className={`font-bold ${done?'':'text-gray-400'}`}>{s.replaceAll('_',' ')}</div><div className="text-xs text-gray-400">{i===0?'Request created':i===1?'Recycler accepted':i===2?'Pickup assigned':i===3?'On the way':i===4?'Arrived at pickup':i===5?'Handover started':'Completed'}</div></div></div>})}</div>{pickup.status==='CANCELLED'?<div className="danger mt-3">This pickup is cancelled and cannot be completed.</div>:pickup.status==='COMPLETED'?<button className="primary mt-3 w-full" onClick={()=>nav('/collector/earnings')}>View earnings</button>:<><button className="primary mt-2 w-full" onClick={advance}>{pickup.status==='REQUESTED'?'Simulate recycler acceptance':pickup.status==='HANDOVER'?'Complete pickup':`Advance to next status`}</button><button className="secondary mt-3 w-full" onClick={()=>nav('/collector/handover')}>Go to handover</button></>}</div></div></AppLayout>}
