"""
schemas/notification.py
--------------------------
Response schema for Notifications. There's no "create" schema here --
notifications are only ever generated by other services in response to
real events (see services/notification_service.py), never created
directly through an API request.
"""

from datetime import datetime

from pydantic import BaseModel


class NotificationOut(BaseModel):
    id: str
    user_id: str
    title: str
    message: str
    type: str
    read: bool
    created_at: datetime

    model_config = {"from_attributes": True}
