import { useEffect,useState } from 'react'
import { CheckCircle2, ShieldAlert, UserRound, Recycle } from 'lucide-react'
import { AppLayout } from '../../layouts/AppLayout'
import { PageHeader } from '../../components/PageHeader'
import { adminService } from '../../services'
export function Collectors(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{adminService.collectors().then(setItems)},[]);return <AppLayout><div className="mx-auto max-w-3xl"><PageHeader title="Collectors"/><div className="space-y-3">{items.map(x=><div key={x.id} className="card flex items-center gap-4 p-5"><div className="rounded-2xl bg-mint p-3 text-leaf"><UserRound/></div><div className="flex-1"><div className="font-black">{x.name}</div><div className="text-sm text-gray-500">{x.area} · {x.lots} lots</div></div><span className="rounded-full bg-mint px-3 py-1 text-xs font-bold text-leaf">{x.status}</span></div>)}</div></div></AppLayout>}
export function Recyclers(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{adminService.recyclers().then(setItems)},[]);return <AppLayout><div className="mx-auto max-w-3xl"><PageHeader title="Recyclers"/><div className="space-y-3">{items.map(x=><div key={x.recycler_id} className="card p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-mint p-3 text-leaf"><Recycle/></div><div className="flex-1"><div className="font-black">{x.name}</div><div className="text-sm text-gray-500">{x.distance_km} km · Radius {x.service_radius_km||10} km</div></div>{x.authorized?<span className="inline-flex items-center gap-1 rounded-full bg-mint px-3 py-1 text-xs font-bold text-leaf"><CheckCircle2 size={14}/> Authorized</span>:<span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700"><ShieldAlert size={14}/> Not authorized</span>}</div><p className="mt-3 text-xs text-gray-500">Accepted: {x.accepted_materials.join(', ')}</p></div>)}</div></div></AppLayout>}
export function AdminTransactions(){return <AppLayout><div className="mx-auto max-w-3xl"><PageHeader title="Transactions"/><div className="card p-6"><div className="text-4xl font-black">₹85,00,000+</div><p className="mt-2 text-gray-500">Prototype aggregate transaction value.</p><div className="mt-6 space-y-3">{['TXN001 · Copper · ₹6,630 · PAID','TXN002 · PCB · ₹3,360 · PAID','TXN003 · Aluminium · ₹2,160 · PENDING'].map(x=><div key={x} className="rounded-2xl bg-gray-50 p-4 font-semibold">{x}</div>)}</div></div></div></AppLayout>}
export function AdminAnalytics(){return <AppLayout><div className="mx-auto max-w-5xl"><PageHeader title="Analytics"/><div className="grid gap-4 md:grid-cols-2">{['Material distribution','Monthly collection','Transaction volume','Price trends'].map((t,i)=><div className="card p-6" key={t}><div className="font-black">{t}</div><div className="mt-5 flex h-44 items-end gap-2 rounded-2xl bg-mint p-4">{Array.from({length:8},(_,n)=><div key={n} className="flex-1 rounded-t-lg bg-leaf/70" style={{height:`${25+((n*(i+2)*17)%65)}%`}}/>)}</div></div>)}</div></div></AppLayout>}
